version: '3.8'
services:
  gocd-server:
    image: gocd/gocd-server:v22.3.0
    container_name: gocd-server
    ports:
      - "8153:8153"
      - "8154:8154"
    environment:
      GOCD_SERVER_JVM_OPTIONS: "-Xms512m -Xmx1024m"
    volumes:
      - gocd-server-data:/godata
      - gocd-server-logs:/go/logs

  gocd-agent:
    image: gocd/gocd-agent-ubuntu-20.04:v22.3.0
    container_name: gocd-agent
    environment:
      - GO_SERVER_URL=http://gocd-server:8153/go
    depends_on:
      - gocd-server
    volumes:
      - gocd-agent-data:/go
    extra_hosts:
      - "gocd-server:172.20.0.2"

  small-app:
    image: node:14-alpine
    container_name: small-app
    build:
      context: ./small-app
    volumes:
      - ./small-app:/usr/src/app
    working_dir: /usr/src/app
    command: npm install && npm run start
    ports:
      - "3000:3000"
    depends_on:
      - gocd-agent

volumes:
  gocd-server-data:
  gocd-server-logs:
  gocd-agent-data:
